#!/usr/bin/env bash
set -euo pipefail

cd "$GITHUB_WORKSPACE"

if [[ "${STP_CONCLUSION:-}" != 'success' ]]; then
	echo '::error::Claude did not complete successfully. Refusing to publish partial changes.' >&2
	exit 1
fi

if [[ "$(git rev-parse HEAD)" != "$(cat "$STP_DIRECTORY/head")" ||
"$(git symbolic-ref --quiet --short HEAD)" != "$(cat "$STP_DIRECTORY/base")" ]]; then
	echo '::error::Claude changed HEAD or switched branches. Refusing to publish; inspect the workflow run.' >&2
	exit 1
fi

report="$STP_DIRECTORY/report.md"
body="$STP_DIRECTORY/body.md"
if [[ ! -s "$report" ]]; then
	echo '::warning::Claude did not write a report. Using a fallback PR description.'
	printf 'The `%s` skill ran but did not write a report. Review the diff and workflow logs for details.\n' "$STP_SKILL" > "$report"
fi
cat "$report" >> "$GITHUB_STEP_SUMMARY"

# Leave room for the footer within GitHub's 65,536-character PR body limit.
# Decode after slicing to avoid emitting a partial UTF-8 character.
node --input-type=module - "$report" "$body" << 'JS'
import { readFileSync, writeFileSync } from 'node:fs'
const [report, body] = process.argv.slice(2)
const content = readFileSync(report)
let text = new TextDecoder().decode(content.subarray(0, 60000), { stream: true })
if (content.length > 60000) {
  text += '\n\n_Report truncated. The full report is in the workflow run summary._\n'
}
writeFileSync(body, text)
JS
printf '\n\n---\n\nGenerated by the `%s` skill in [this workflow run](%s).\n' "$STP_SKILL" "$STP_RUN_URL" >> "$body"
